apiVersion: v1
kind: Service
metadata:
  name: {{ include "express.fullname" . }}
  labels:
    {{- include "express.labels" . | nindent 4 }}
  namespace: "express"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "express.selectorLabels" . | nindent 4 }}
