apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /apple
          backend:
            serviceName: webapp1-svc-n
            servicePort: 80
        - path: /banana
          backend:
            serviceName: webapp2-svc-n
            servicePort: 81
        - path: /
          backend:
            serviceName: webapp2-svc-n
            servicePort: 81
