apiVersion: v1
kind: Service
metadata:
  name: webapp1-svc-n
  labels:
    app: webapp1
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    author: praveen

---

apiVersion: v1
kind: Service
metadata:
  name: webapp2-svc-n
  labels:
    app: webapp2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 81
  selector:
    author: praveen

