---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv
  labels:
    type: aws-pv
  namespace: {{ .Values.space }}
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-072118726b2f56829
    fsType: xfs